### ISSUE TITLE
BackEnd>Storage Diagrams

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#12]
BackEnd>Storage>User>beaconId
- if the user is allowed to join more than one beacon, consider changing attribute name to "beacons" (unless I understand the UML wrong)
- inconsistent name, beaconId, vs beaconID in the Beacon table.

BackEnd>Storage>User>courseCode
- if the user is allowed more than one course, consider changing attribute name to "courses" (unless I understand the UML wrong)

**Comment by Amandeep-G** [comment]
The multiplicity in square brackets showcases how many beacons the user can join so [0..*] (zero to many) which is I believe how it should be in UML. Also we are using beaconId and courseCode as they are foreign keys from their respective tables.
