### ISSUE TITLE
Class Diagrams individually

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#14]
Class Diagrams>User
- Join/Leave methods seem redundent when the Beacon class has addMember and removeMember (also noted in Class Diagrams>Beacon)
- consider moving Invite function to registered user, so guests cannot be invited
- method naming style inconsistent with the rest of the diagrams.

Class Diagrams>Registered User
- no hosted beacons attribute (ignore if we don't need this)
- consider moving all closeBeacon, extendBeacon, relocateBeacon to the beacon class

Class Diagrams>Beacon
- addMember and removeMember seem redundent when the User class has Join and LeaveBeacon. (also noted in Class Diagrams>User)
- removeMember doesnt have any parameters

Class Diagrams>Chat
- chat constructor not capitalized

Class Diagrams> Message
-"message class is package access" consider changing "is" to "has"

**Comment by chhomchhom** [comment]
Hi there,

I believe I have made the correct changes as suggested. However regarding join/leave and the addMember/removeMmeber methods. I think it makes sense as the User class and all that inherent it should be able to leave and/or join beacons per the user's choice but the addMember/removeMember is for the registered user that is hosting a beacon to have the choice to add and/or remove someone from their beacon.

Hope that makes sense. Thanks!
