### ISSUE TITLE
2.2.x Concurrent Process Decomposition

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#15]
2.2.1 Home Window
consider re-describing this
"contains already created beacons to join"
as a "list" of beacons already created.

2.2.2 LoginWindow
"contains the field for Registered Users to input email and password"
consider pluralizing "field" and changing "input email" to "input an email"

- specify what "Email, confirm Email, password, confirm password." are/is (input fields?)

2.2.3. BeaconCreationWindow
- doesn't describe a "finish" or "confirm" button (we probably need one lol)

2.2.5. UserDiscoveryWindow
- describes what is being displayed as "users of the site", maybe change to "registered users" to be more clear as to who/what is being displayed

2.2.6. ChatWindow
- doesn't specify location of the chat window, just says "bottom corner"

**Comment by MitchMarino** [comment]
Hi Matthew,

Thank you for the SQA. 
I have implemented the adjustments you recommended and the section is much clearer / better overall. It will be evident in the next version.

Best,
Mitch
