### ISSUE TITLE
Data Decomposition methods

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#17]
RegisterUser()
- grammar, "take all fields disregarding empty field", pluralization is missing
- "and putting it into" change to "and put it into"
- capitalize "user class" to "User class"
- missing a period at the end of the paragraph

GuestUser()
- run on first sentence.
- described as "A new constructor in the user class that inherits from the User class". doesn't really make sense.
- capitalization of "User" is missing
- guests are given a "temporary id", are we giving them a temporary id or a temporary username?
- missing a period at the end of the paragraph

RegisteredUser()
- missing a period at the end of the paragraph
- the User class is described as "the class User" when in the previous two paragraphs it is "the User class"
- "interface(Creating a beacon)", needs a space and un-capitalize "Creating"

**Comment by CalvinJW** [comment]
Removed, wasn't supposed to be there, my bad :)
