### ISSUE TITLE
4.1 Module detailed design grammar issues

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#20]
4.1 Logout
- the second point is two questions lmao (unfinished), remove or change to the real psuedocode.

4.1 EditProfile
- bad desctipion (literally has the words "bad description")

4.1 CreateBeacon
- again, bad desctipion (literally has the words "bad description")

4.1 FailedCreation
- has a question as the first step in psuedocode (unfinished?)

4.1 Validation Methods
- these methods are not described at all.
- "Forced to use a username", no context for this line.

4.1 CloseBeacon
- in the description, "beacon" is not capitalized, but in the other descriptions it is.

4.1 RelocateBeacon
- description, in the same sentence beacon is not capitalized, and capitalized.

4.1 JoinBeacon
- beacon is not capitalized in the psuedocode

4.1 NotifyUser
- beacon is not capitalized in the psuedocode

4.1 DisplayResults
- Beaconlist and BeaconList are used, inconsistent

**Comment by MitchMarino** [comment]
Hey Matthew,

Thank you for your SQA.
The changes you have suggested have been implemented for the next version.

Best,
Mitch
