### ISSUE TITLE
Class Diagram feedback

### ISSUE THREAD

**Issue by Jake-L** [cp317/Design#21]
- Registered User -> no getters, why do we have setEmail etc and editProfile which appear to do the same thing?
- should Registered User have a createBeacon method?
- why does getOpenBeacons take parameters? Is it just supposed to return all the Beacons that user has created?
- Guest User -> registerUser method should return the newly created Registered User object
- Class names should not have spaces
- Course not uniquely identified
- Course not getters for attributes other than description
- add documentation on why anyone can change the description but none of the other attrbutes
- Beacon constructor should include Course
- Beacon -> change addMember to inviteUser
- Beacon -> removeMember should be removeUser, which removes the User object
- Beacon -> getCourseCode returns course object, should be called getCourse
- Beacon -> what is purpose of relocateBeacon? why does it take another Beacon as a parameter, and what is the string it returns? change to setLocation?
- Beacon -> change updateEndTime to setEndTime and updateStartTime to setStartTime
- Beacon -> closeBeacon should not take a Beacon as a parameter
- Beacon -> remove extendBeacon function, or change to setLocation
- Beacon -> not clear what calcTimeRemaining does
- If chat has chatType, can we remove BeaconChat, CourseChat, and PrivateChat?

**Comment by Amandeep-G** [comment]
made changes as requested
