### ISSUE TITLE
Database Diagram feedback

### ISSUE THREAD

**Issue by Jake-L** [cp317/Design#22]
Database Design Diagrams:
- Beacon should be associated with exactly 1 course, can't not have a course
- I'd say Beacon should also have exactly 1 chat key, even if not one has chatted it could still have the key generated when the Beacon is created
- userName should be primary key of User table, userKey is unnecessary
- Chat table -> chat key should be broken up into an integer key and a char chatType 
- Beacon Tag database -> attributes: tagName (string unique key), iconLink (link to icon image to be displayed on beacon)
- Beacon table tab attribute is an array of Tag objects

Database Diagram (the one with lines connecting the databases):
- add direction of relationships (arrow from beacon to chat because chat does not have any foreign keys from beacon) (bi-directional lines have no arrows)
- what is the difference between CreateBeacon and RegisterBeacon?? 
- remove DeleteCourse
- set multiplicity of course - chat relationship to 1

location for all diagrams and documentation should be two attributes: lat and lng, both either doubles or floats

**Comment by Amandeep-G** [comment]
made the changes
