### ISSUE TITLE
General Feedback and Changes

### ISSUE THREAD

**Issue by shujaatbidar** [cp317/Design#24]
1.2 Scope
*This document guides the software developers

Database in the table instead of table in the database

2.0
What is used to store -> weak

2.1
Foreign key (0:1) implies there can be a beacon without a course
Implies username is not unique (what’s the difference between username and user key?)
Don’t see the benefit of having user key
Use chat type
Could have beacon tag table in database
What’s the point of editProfile if theres setBio, SetGra, setEmail etc.
Why does getOpenBeacon have school as argument(can user be associated with more than on school?)
If user types in UW how does google api know which UW -> be more creative with google api
How is course code going to be unique?
Why can you only change course description but not course name, course code etc.
Why is course not in beacon constructor?
relocateBeacon ->setLocation, updateEndTime -> setEndTime, updateStartTime -> setStartTime
What’s the difference between extendBeacon and updateEndTime?

Indicate direction clearly
Difference between createBeacon and registerBeacon?
shouldn’t have delete course

2.3
all data is handled
Get rid of future tense

**Comment by Amandeep-G** [comment]
made the changes
