### ISSUE TITLE
Database Diagram

### ISSUE THREAD

**Issue by wuwica** [cp317/Design#25]
Modify the dependency to reflect the beacon table, 1..* atleast one 1 user for each beacon
[![https://gyazo.com/4cec848653c27d54100a853a9120a672](https://i.gyazo.com/4cec848653c27d54100a853a9120a672.png)](https://gyazo.com/4cec848653c27d54100a853a9120a672)

**Comment by Amandeep-G** [comment]
Jake told me that the host is not counted as member so that means beacons can have 0 members and 1 host. I am still updating the diagrams, create another issue if you find one, once they are updated.
