### ISSUE TITLE
Class Diagram Issues 

### ISSUE THREAD

**Issue by Jake-L** [cp317/Design#3]
Class Diagram Issues
- There are classes for beacon chat and private chat, but it should have course chat as well for the course pages
- I see Beacon has private methods to update the startTime and endTime, what calls these methods? I see the extendBeacon function in registeredUser, but the user class shouldn't be able to access the Beacon class' private methods. Consider making those methods public or adding a public updateBeacon function to Beacon that calls those private methods
- The Course objects getOpenBeacons method is probably unnecessary, we need a more general getOpenBeacons function where you can search by school name and course code
- What is the point of the updateDay method within beacon? Day is not an attribute and there are already methods to update the startTime and endTime, so I don't see any use for it.

**Comment by chhomchhom** [comment]
Points:
1. I've added the chat
2. I chose to make the methods public 
3. I've moved the getOpenBeacons from the class Course to the class Registered User. 
4. I had a different idea of how beacon's time was split up. i got rid of updateDay method as well as the Day day parameters in the constructor of Beacon
