### ISSUE TITLE
Chat class changes

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/Design#31]
- chatLog attribute should be named messages.
- add a new users : User[0 .. *] attribute.
- add new private method checkPrivateChatExists() : Promise.
- add new public method createNewMessage(String msgString, String userId) : void.
- add new private method createTimestamp() : void.
- add new public method getMessages() : Message[0 .. *].
- add new public method getUsers() : User[0 .. *].
- add new private method queryForChatMessages(): Promise.
- add new public method setUsers(User[] users) : void.
- change updateChat(String msgString): void to updateChat() : void.
- add new public method writePrivateChatId() : void.

**Comment by Amandeep-G** [comment]
Done.
