### ISSUE TITLE
ClassDiscoveryWindow removed

### ISSUE THREAD

**Issue by orchidami** [cp317/Design#32]
The ClassDiscoveryWindow was removed but it is still mentioned in the design doc.

Also, under 3.0 Interface Description - Module Interface, the description for the ProfilePageWindow is missing.

**Comment by Nganstar** [comment]
Hey can you specify where you saw ClassDiscoveryWindow was mentioned in the design doc. 

Also, what description are you referring for the ProfilePageWindow. Since the only descriptions are in the tables and there already are descriptions.

**Comment by chhomchhom** [comment]
Design Document was checked over and could not identify these issues
