### ISSUE TITLE
Database Class Diagram Issues

### ISSUE THREAD

**Issue by Jake-L** [cp317/Design#4]
Database Class Diagram Issues
- I think all the Beacon methods should be public?
- GuestUser should have a register method that allows them to create a username, password, and enter their email address. Then they would be transferred into a RegisteredUser class.
- Looking at the Chat class between the Class Diagram and the Database Class Diagram, it is a little confusing how we switch from having a message class to just having a chatLot string. I understand why chatLog is a string, I'm assuming it will just be a text file containing a line for each message in the format "msgString, timeStamp, sender" which can be converted into a Message Object. However, I could only draw that conclusion because I've been involved in lot of discussions, this needs to be clearly stated somewhere.

**Comment by Amandeep-G** [comment]
Ok I've made all the beacon methods public and I will add a description regarding the chat under the diagram in the design doc to clarify.

I believe @chhomchhom will update GuestUser with a function/method for registering the guest

**Comment by chhomchhom** [comment]
I've added the method for GuestUser, thanks for the feed back!
