### ISSUE TITLE
1.3 Definitions

### ISSUE THREAD

**Issue by myounatan** [cp317/Design#9]
1.3.3 userdb definition
- do we store users credentials or a list of users and their credentials? consider changing to the phrase "which stores a list of all users and their credentials"
1.3.2 chatdb definition
- not clear as to what a "chat" is, kind of ambiguous, the phrase "logs all chat" could be changed to "logs all chat messages" or "logs chat messages"

**Comment by CalvinJW** [comment]
changed to chat messages, for clarity.
